name: Update Homebrew Cask

on:
  repository_dispatch:
    types: [update-cask]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  update-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update cask file
        run: python update_cask.py

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update cask for latest release"
          git push

      - name: Create pull request to homebrew-cask
        if: steps.changes.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
        run: |
          echo "Cask updated successfully!"
          echo "You can now submit this to homebrew-cask manually or create a PR."